### ISSUE TITLE
3rd optional parameter

### ISSUE THREAD

**Issue by Ranger2000** [hfiref0x/UACME#11]
Would it be possible to allow more than 2 parameters, so that it can be committed a parameter to the elevated program? Like "akagi64.exe 3 notepad.exe c:\Windows\System32\drivers\etc\hosts"
Currently the parameter "c:\Windows\System32\drivers\etc\hosts" is not passed to notepad.exe.

This is a request #7 from 7 Jul 2016, which was closed without comment.
Version 2.5.5. was testet therefore but the third parameter did not pass.

**Comment by hfiref0x** [comment]
Hello,
why you need this? For your example you can create elevated shortcut - documented working way without any hacks. This tool is sort of hacktool that affects system, not something that should be used on regular basis.

To execute UACMe in way you posted add quotes to the command line, e.g.

akagi64 27 "c:\windows\system32\notepad.exe c:\windows\system32\drivers\etc\hosts" <- this functionality was here since beginning.

No additional fuctionality regarding 3rd, 4rd ... etc parameters will be added.
