### ISSUE TITLE
WinSxS DLL forwarding question

### ISSUE THREAD

**Issue by L3cr0f** [hfiref0x/UACME#16]
Hi hfiref0x,
I love your project and I want to ask you a question regarding methods 21 and 22, during the DLL hijacking how do you perform the forwarding to the legit DLL?

I ask you this because I've developed a WinSxS bypass UAC abusing dccw.exe (PoC in my github: github.com/L3cr0f/DccwBypassUAC) and the only way I found to do so was using '#pragma comment (linker, "/export...', but you don't use it.

PD: If you want to integrate my PoC in UACME, I'll be really happy :)

Thank you beforehand.

**Comment by hfiref0x** [comment]
Hello,
you don't need to forward anything. Goal of running target app is to force it load and execute your code. What next will be with target app is irrelevant and it should be terminated anyway. Thus enough to add dummy exports required by target app just to get it load.

Your project is different from method 21 in general by only target app (dccw.exe) and target dll (GdiPlus.dll). There about 50+ autoelevated binaries on for example Windows 8.1, 60+ on Windows 10. Most of them can be directly dll hijacked with DotLocal. There is no sense in adding anything just because it abuses different dll or exe if method already present (and duplicate already with method 22 but it give some additional fun as jumping to "nt authority\system" from uac service). The same why I will never add "TpmInit Uac Bypass" because it in fact the same Leo Davidson method again and again but with different dll and executable and this project already have multiple combinations of the same Leo Davidson method, so what is the point to do this again for another method?

In contrary about so called "fileless" methods: they maybe all based on the same registry manipulations (registering/altering handler for file association, adding missing app entry) but all different in implemenation - one abuses IsolatedCommand, second AppPaths, third requires DelegateExecute.

The basic set of requirements when I consider adding something to UACMe:

1) Abused by malware

I've not seen DotLocal abused by malware so far. Not 21/22 not yours dccw+gdiplus.

2) Totally new technique - like for example method 35, or innovation based on old method e.g. 32, despite the fact it is based on Leo Davidson IFileOperation to deliver payload the second part is completely new and unseen anywhere

Your method is derivative from already included.

3) Old method patched, but new working method based on old method is discovered (example sysprep methods)

So for example if MS will add "workaround" for comctl32.dll dll hijack via DotLocal but this workaround won't affect GdiPlus.dll then yes I will add your method as derivative of 21.

**Comment by L3cr0f** [comment]
That's true! Thank you anyway ;)

**Comment by hfiref0x** [comment]
The time for your method is come ;-) Microsoft "fixed" sysprep method by banning unsigned dll (again).

**Comment by L3cr0f** [comment]
Great! Now let's see how much time Microsoft takes to "patch" it hahahahaha

**Comment by akayn** [comment]
hey just for ya to know same story as sysprep & dccw i found a new working target by the exact same method if dccw will ever stop working printui.exe under syswow64, i simply inject to explorer a dll to invoke iofileoperation (cuz im lazy) here's a poc... https://github.com/akayn/Arsenal/tree/master/UacByPass
