### ISSUE TITLE
Naka problem

### ISSUE THREAD

**Issue by shiad** [hfiref0x/UACME#43]
Hello,

When i generate new .cd using Naka64 command line and replace it with ripositories original .cd, i get trouble and [method] execution failed. e.g:
`C:\Users\user\Desktop\Naka64.exe C:\Path\To\Example\Project\Fubuki.exe`
Output: .key and .cd files. Copy .cd in Akagai\bin path and recompile solution. But failed to execute Akagai64.exe with Fubuki-specific methods. We have no error(s) and nothing happen. Whats wrong?!
note that i set build events to no, point to #12

Thanks for this great repo!

**Comment by hfiref0x** [comment]
Hello,

when you regenerated these cd files and replaced original in Akagi/Bin you have to also update Akagi/secrets.h, because it now contain invalid keys data for decrypt.

naka --stable will produce secrets blob file.

If you update x64 binaries secrets64.bin will be produced by Naka. 
If you update x86 binaries secrets32.bin will be produced by Naka.

This bin file is a combination of all *.key files generated in current Naka directory.

Open secrets bin file with hex editor and copy it contents as C array. Example with WinHex

![secrets](https://user-images.githubusercontent.com/10708977/51302402-ce32d380-1a64-11e9-945c-ef396e31dad5.png)

Next open Akagi/secrets.h and update g_bSecrets array with this new data. Make sure array size is correct for new data and array name is g_bSecrets.

e.g.

![secrets2](https://user-images.githubusercontent.com/10708977/51302702-bc9dfb80-1a65-11e9-8778-a09dc2f04121.png)

Rebuild Akagi next. Now it should be able to decrypt new cd files. Note if you even didn't changed these dlls but recompiled them and replaced cd files in Akagi\Bin you still will have to regenerate secrets array because PE files have changed due to different timestamps and decryption procedure rely on PE header hash data.

Repeat everything again when/if cd files regenerated.

**Full example.**

Assume you have project in C:\Project
Assume you have Compress folder in C:\Project for Naka needs.
Assume you have batch file copy.cmd that copies required files to C:\Project\Compress
Assume you have work.cmd that calls Naka for each of these copied files and generate secrets blobs.
Assume you have compiled Naka64.exe in C:\Project\Compress and this is Naka from current uacme version.

1) compile dlls
2) move them to C:\Project\Compress folder with copy.cmd
3) pack and encrypt them with work.cmd
4) copy *.cd files to Akagi\bin
5) generate secrets.bin (for each 32/64)
6) copy secrets.bin (for each 32/64) as C array to akagi/secrets.h replacing original as shown above.
7) rebuild akagi

Where copy.cmd looks like (correct this for your paths used)

> copy C:\Project\Akatsuki\output\x64\Release\Akatsuki64.dll C:\Project\Compress\Akatsuki64.dll /y
> copy C:\Project\Fubuki\output\Win32\Release\Fubuki32.dll C:\Project\Compress\Fubuki32.dll /y
> copy C:\Project\Fubuki\output\x64\Release\Fubuki64.dll C:\Project\Compress\Fubuki64.dll /y
> copy C:\Project\Hibiki\output\Win32\Release\Hibiki32.dll C:\Project\Compress\Hibiki32.dll /y
> copy C:\Project\Hibiki\output\x64\Release\Hibiki64.dll C:\Project\Compress\Hibiki64.dll /y
> copy C:\Project\Ikazuchi\output\Win32\Release\Ikazuchi32.dll C:\Project\Compress\Ikazuchi32.dll /y
> copy C:\Project\Ikazuchi\output\x64\Release\Ikazuchi64.dll C:\Project\Compress\Ikazuchi64.dll /y
> copy C:\Project\Chiyoda\output\x64\Release\Chiyoda64.dll C:\Project\Compress\Chiyoda64.dll /y
> copy C:\Project\Fujinami\output\Fujinami.dll C:\Project\Compress\Fujinami.dll /y

and work.cmd looks like (correct this for your paths used)

> naka64 C:\Project\Compress\Akatsuki64.dll
> naka64 C:\Project\Compress\Fubuki64.dll
> naka64 C:\Project\Compress\Fubuki32.dll
> naka64 C:\Project\Compress\Hibiki32.dll
> naka64 C:\Project\Compress\Hibiki64.dll
> naka64 C:\Project\Compress\Ikazuchi32.dll
> naka64 C:\Project\Compress\Ikazuchi64.dll
> naka64 C:\Project\Compress\Fujinami.dll
> naka64 C:\Project\Compress\Kamikaze.msc
> naka64 C:\Project\Compress\Kongou32.dll
> naka64 C:\Project\Compress\Kongou64.dll
> naka64 C:\Project\Compress\Chiyoda64.dll
> 
> naka64 --stable
> 
> copy C:\Project\Compress\Akatsuki64.cd C:\Project\Akagi\Bin\Akatsuki64.cd /y
> copy C:\Project\Compress\Fubuki32.cd C:\Project\Akagi\Bin\Fubuki32.cd /y
> copy C:\Project\Compress\Fubuki64.cd C:\Project\Akagi\Bin\Fubuki64.cd /y
> copy C:\Project\Compress\Hibiki32.cd C:\Project\Akagi\Bin\Hibiki32.cd /y
> copy C:\Project\Compress\Hibiki64.cd C:\Project\Akagi\Bin\Hibiki64.cd /y
> copy C:\Project\Compress\Ikazuchi32.cd C:\Project\Akagi\Bin\Ikazuchi32.cd /y
> copy C:\Project\Compress\Ikazuchi64.cd C:\Project\Akagi\Bin\Ikazuchi64.cd /y
> copy C:\Project\Compress\Fujinami.cd C:\Project\Akagi\Bin\Fujinami.cd /y
> copy C:\Project\Compress\Kamikaze.cd C:\Project\Akagi\Bin\Kamikaze.cd /y
> copy C:\Project\Compress\Kongou32.cd C:\Project\Akagi\Bin\Kongou32.cd /y
> copy C:\Project\Compress\Kongou64.cd C:\Project\Akagi\Bin\Kongou64.cd /y
> copy C:\Project\Compress\Chiyoda64.cd C:\Project\Akagi\Bin\Chiyoda64.cd /y
> 
> pause

**Comment by shiad** [comment]
Thanks alot!
What happen when i use 1/some module(s) in project? How generate secrets file? Considering key size and etc..

**Comment by hfiref0x** [comment]
It is all listed above. Naka generates secrets file when it run with "--stable" parameter (see work.cmd). Secrets blob generated from *.key files. If you use just a single dll in project then you can simple copy contents of it *.key file to secrets.h array the same as show above. This g_bSecrets array in secrets.h it is just an array of DCK_HEADER structs.

**Comment by shiad** [comment]
Thanks much!
