### ISSUE TITLE
Why do you use the native api for functions that are exposed in Win32?

### ISSUE THREAD

**Issue by repnz** [hfiref0x/UACME#58]
Hey, I have a general question about the implementation of UACME. I've noticed you use the ntdll.dll api directly (by using ntos.h..). Why do you use this api and not Win32? For example, you use the following functions which exist in Win32: 

- RtlSecureZeroMemory
- RtlExpandEnvironmentStrings
- NtPrivilegeCheck
- ...

I understand that some specific functions are not available in Win32, but why use all the other functions through ntdll?

**Comment by hfiref0x** [comment]
Well 1) because _I can._ 2) Win32 API is upper level layer full of ineffective code which functionality I don't need. 3) Win32 API error codes packs multiple actually completely different NTSTATUS values into one turning it into unmeaningful trash. And 4) some dlls need only ntdll in dependencies.

According to your list:
RtlSecureZeroMemory is an inline function. It doesn't exports from anywhere. 
RtlExpandEnvironmentStrings/NtPrivilegeCheck used in utils.c which is a part of dlls shared code. Some of the dlls require only NTDLL dependencies to load (e.g. verifier dll).

**Comment by repnz** [comment]
Thanks for your answer:)
