### ISSUE TITLE
Method 56 may not work

### ISSUE THREAD

**Issue by L1B0** [hfiref0x/UACME#94]
I test method 56 on windows10 18363.
But only run WSReset.exe，cmd.exe doesn't run.
And I find WSReset.exe doesn't query the registry value HKEY_CURRENT_USER\Software\Classes\AppX82a6gwre4fdg3bt635tn5ctqjf8msdd2\Shell\open\command by using procmon.

**Comment by hfiref0x** [comment]
Could be. This method since beginning was questionable. As usual in this case, later I will do tests on clean install of 18363 and if it works for me then I will close this issue. If it does not work somewhere then this method will be marked as fixed.

**Comment by hfiref0x** [comment]
I'm unable to reproduce your report on fresh install of 18363 nor on patched 18363.1256. I guess this is somewhat related to your system configuration / type. As original author of this method never bothered to figure out _exact_ description of how this exploit works and what _exactly_ triggers it, I can't provide any further details too as digging into that method has no sense due to wide range of better methods available.

**Comment by L1B0** [comment]
Does it mean that method 56 doesn't work on your windows 18363?
Thanks for your reply!

**Comment by hfiref0x** [comment]
No, it works well here on both fresh and full patch installs of 18363.

**Comment by L1B0** [comment]
Ok, maybe I made something wrong on somewhere.
Thanks!
