### ISSUE TITLE
UAC bypass in computerdefaults.exe using protocol hijacking

### ISSUE THREAD

**Issue by lafwaN** [hfiref0x/UACME#99]
Hi,
I made a repo showcasing a UAC bypass over here: https://github.com/lafwaN/mychoppa

It works on Windows 10 LTSC 1809, it should also hopefully work on some other versions though. I would like you to take a look at it.

Thanks,
Nawfal

**Comment by hfiref0x** [comment]
Hello,
it is the same as method 67 but with computerdefaults.exe as target. Fodhelper/ComputerDefaults pair ms-settings hijacking is known for years and since this repo already has 3 methods (2 for hijacking ms-settings sregistry entries for FodHelper/ComputerDefaults) and 1 for hijacking ms-settings protocol for FodHelper) there is no need in another one.

**Comment by lafwaN** [comment]
That is understandable. Thank you for reviewing my issue.
